using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;

namespace SimpleSeleniumSupport.Reporting
{
    /// <summary>How the source report was originally produced.</summary>
    public enum ReportSourceType
    {
        /// <summary>Folder output from <see cref="TestRunReportExporter.Export"/> (contains data.json + manifest.json).</summary>
        FolderBased,
        /// <summary>Single self-contained .html from <see cref="TestRunReportExporter.ExportSingleFile"/>.</summary>
        SingleFile
    }

    /// <summary>Metadata and results for a report found during a <see cref="ConsolidatedReportBuilder.Discover"/> scan.</summary>
    public sealed class DiscoveredReport
    {
        /// <summary>Report name extracted from manifest.json or the sss:report-name meta tag.</summary>
        public string ReportName { get; init; } = "";

        /// <summary>Absolute path to the report folder (FolderBased) or .html file (SingleFile).</summary>
        public string SourcePath { get; init; } = "";

        /// <summary>Whether this report came from a folder or a single HTML file.</summary>
        public ReportSourceType SourceType { get; init; }

        /// <summary>Number of test results found in this report.</summary>
        public int TestCount { get; init; }

        /// <summary>All deserialized test results from this report.</summary>
        public IReadOnlyList<TestResult> Results { get; init; } = [];
    }

    /// <summary>
    /// Scans a root folder for reports generated by <see cref="TestRunReportExporter"/>,
    /// merges their results, and produces a single consolidated report.
    /// <para>
    /// Both folder-based reports (<c>data.json</c> + <c>manifest.json</c>) and
    /// single-file HTML reports are discovered automatically.
    /// </para>
    /// </summary>
    public static class ConsolidatedReportBuilder
    {
        // ── Public API ──────────────────────────────────────────────────────────

        /// <summary>
        /// Scans <paramref name="rootFolder"/> for all SimpleSeleniumSupport reports,
        /// merges their results, and exports a folder report
        /// (<c>index.html</c> + <c>data.json</c> + <c>manifest.json</c>).
        /// </summary>
        /// <param name="rootFolder">Root directory to scan for source reports.</param>
        /// <param name="outputFolder">Directory where the consolidated report folder is created.</param>
        /// <param name="reportName">
        ///   Display name for the consolidated report.
        ///   Defaults to <c>"Consolidated Report (N runs)"</c>.
        /// </param>
        /// <param name="recursive">
        ///   When <see langword="true"/> (default), searches all subdirectories.
        ///   When <see langword="false"/>, searches only the immediate children of <paramref name="rootFolder"/>.
        /// </param>
        /// <returns>Absolute path of the generated report folder.</returns>
        public static string Export(
            string rootFolder,
            string outputFolder,
            string? reportName = null,
            bool recursive = true)
        {
            var discovered = ScanReports(rootFolder, recursive, outputFolder);
            var allResults = discovered.SelectMany(d => d.Results).ToList();
            reportName ??= $"Consolidated Report ({discovered.Count} runs)";
            return TestRunReportExporter.ExportConsolidated(allResults, outputFolder, reportName);
        }

        /// <summary>
        /// Scans <paramref name="rootFolder"/> for all SimpleSeleniumSupport reports,
        /// merges their results, and exports a single self-contained HTML file.
        /// </summary>
        /// <param name="rootFolder">Root directory to scan for source reports.</param>
        /// <param name="outputFolder">Directory where the consolidated .html file is created.</param>
        /// <param name="reportName">
        ///   Display name for the consolidated report.
        ///   Defaults to <c>"Consolidated Report (N runs)"</c>.
        /// </param>
        /// <param name="recursive">
        ///   When <see langword="true"/> (default), searches all subdirectories.
        /// </param>
        /// <returns>Absolute path of the generated .html file.</returns>
        public static string ExportSingleFile(
            string rootFolder,
            string outputFolder,
            string? reportName = null,
            bool recursive = true)
        {
            var discovered = ScanReports(rootFolder, recursive, outputFolder);
            var allResults = discovered.SelectMany(d => d.Results).ToList();
            reportName ??= $"Consolidated Report ({discovered.Count} runs)";
            return TestRunReportExporter.ExportSingleFileConsolidated(allResults, outputFolder, reportName);
        }

        /// <summary>
        /// Scans <paramref name="rootFolder"/> for all SimpleSeleniumSupport reports,
        /// runs AI failure analysis on every discovered failed test, merges the results,
        /// and exports a folder report (<c>index.html</c> + <c>data.json</c> + <c>manifest.json</c>).
        /// </summary>
        /// <param name="rootFolder">Root directory to scan for source reports.</param>
        /// <param name="outputFolder">Directory where the consolidated report folder is created.</param>
        /// <param name="reportName">Display name. Defaults to <c>"Consolidated Report (N runs)"</c>.</param>
        /// <param name="recursive">Search all subdirectories when <see langword="true"/> (default).</param>
        /// <param name="analysisOptions">AI failure analysis configuration. <see langword="null"/> uses defaults.</param>
        /// <param name="sanitize">Optional sanitization applied to the final export.</param>
        /// <param name="ct">Optional cancellation token.</param>
        /// <returns>Absolute path of the generated report folder.</returns>
        public static async Task<string> AnalyzeAndExportAsync(
            string rootFolder,
            string outputFolder,
            string? reportName = null,
            bool recursive = true,
            AI.FailureAnalysisOptions? analysisOptions = null,
            AI.Sanitization.SanitizationOptions? sanitize = null,
            CancellationToken ct = default)
        {
            var discovered = ScanReports(rootFolder, recursive, outputFolder);
            var allResults = discovered.SelectMany(d => d.Results).ToList();
            reportName ??= $"Consolidated Report ({discovered.Count} runs)";
            var analyzer = new AI.TestFailureAnalyzer(analysisOptions);
            await analyzer.AnalyzeAsync(allResults, ct).ConfigureAwait(false);
            return TestRunReportExporter.ExportConsolidated(allResults, outputFolder, reportName);
        }

        /// <summary>
        /// Scans <paramref name="rootFolder"/> for all SimpleSeleniumSupport reports,
        /// runs AI failure analysis on every discovered failed test, merges the results,
        /// and exports a single self-contained HTML file.
        /// </summary>
        /// <param name="rootFolder">Root directory to scan for source reports.</param>
        /// <param name="outputFolder">Directory where the consolidated .html file is created.</param>
        /// <param name="reportName">Display name. Defaults to <c>"Consolidated Report (N runs)"</c>.</param>
        /// <param name="recursive">Search all subdirectories when <see langword="true"/> (default).</param>
        /// <param name="analysisOptions">AI failure analysis configuration. <see langword="null"/> uses defaults.</param>
        /// <param name="sanitize">Optional sanitization applied to the final export.</param>
        /// <param name="ct">Optional cancellation token.</param>
        /// <returns>Absolute path of the generated .html file.</returns>
        public static async Task<string> AnalyzeAndExportSingleFileAsync(
            string rootFolder,
            string outputFolder,
            string? reportName = null,
            bool recursive = true,
            AI.FailureAnalysisOptions? analysisOptions = null,
            AI.Sanitization.SanitizationOptions? sanitize = null,
            CancellationToken ct = default)
        {
            var discovered = ScanReports(rootFolder, recursive, outputFolder);
            var allResults = discovered.SelectMany(d => d.Results).ToList();
            reportName ??= $"Consolidated Report ({discovered.Count} runs)";
            var analyzer = new AI.TestFailureAnalyzer(analysisOptions);
            await analyzer.AnalyzeAsync(allResults, ct).ConfigureAwait(false);
            return TestRunReportExporter.ExportSingleFileConsolidated(allResults, outputFolder, reportName);
        }

        /// <summary>
        /// Scans <paramref name="rootFolder"/> and returns metadata for every discovered
        /// SimpleSeleniumSupport report without exporting anything.
        /// </summary>
        /// <param name="rootFolder">Root directory to scan.</param>
        /// <param name="recursive">
        ///   When <see langword="true"/> (default), searches all subdirectories.
        /// </param>
        /// <returns>Discovered reports sorted by source path.</returns>
        public static IReadOnlyList<DiscoveredReport> Discover(
            string rootFolder,
            bool recursive = true)
            => ScanReports(rootFolder, recursive, excludeFolder: null);

        // ── Scan ────────────────────────────────────────────────────────────────

        private static IReadOnlyList<DiscoveredReport> ScanReports(
            string rootFolder, bool recursive, string? excludeFolder)
        {
            var searchOption = recursive ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly;
            var results  = new List<DiscoveredReport>();
            var skipDirs = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            // Exclude the output folder from directory-level scanning only when it is a
            // DIFFERENT directory from rootFolder. When they are the same (e.g. "Reports"),
            // excluding the folder would also skip all source reports in it.
            // Self-exclusion of consolidated reports is instead handled per-file via the
            // sss:report-type="consolidated" meta tag and the reportType manifest field.
            if (!string.IsNullOrEmpty(excludeFolder))
            {
                var fullExclude = Path.GetFullPath(excludeFolder);
                var fullRoot    = Path.GetFullPath(rootFolder);
                if (!string.Equals(fullExclude, fullRoot, StringComparison.OrdinalIgnoreCase))
                    skipDirs.Add(fullExclude);
            }

            // Step 1 — Folder-based reports: locate every data.json that has a sibling manifest.json
            foreach (var dataJsonPath in Directory.EnumerateFiles(rootFolder, "data.json", searchOption))
            {
                var dir = Path.GetFullPath(Path.GetDirectoryName(dataJsonPath)!);
                if (skipDirs.Contains(dir)) continue;

                var manifestPath = Path.Combine(dir, "manifest.json");
                if (!File.Exists(manifestPath)) continue;

                var report = TryReadFolderReport(dataJsonPath, manifestPath);
                if (report != null)
                {
                    results.Add(report);
                    skipDirs.Add(dir);  // don't also scan the index.html in this folder
                }
            }

            // Step 2 — Single-file HTML reports: any *.html that is not index.html and not in a
            //           folder that already yielded a folder-based report.
            foreach (var htmlPath in Directory.EnumerateFiles(rootFolder, "*.html", searchOption))
            {
                var dir = Path.GetFullPath(Path.GetDirectoryName(htmlPath)!);
                if (skipDirs.Contains(dir)) continue;
                if (string.Equals(Path.GetFileName(htmlPath), "index.html", StringComparison.OrdinalIgnoreCase))
                    continue;

                var report = TryReadSingleFileReport(htmlPath);
                if (report != null)
                    results.Add(report);
            }

            return results.OrderBy(r => r.SourcePath, StringComparer.OrdinalIgnoreCase).ToList();
        }

        // ── Folder-based reader ─────────────────────────────────────────────────

        private static DiscoveredReport? TryReadFolderReport(string dataJsonPath, string manifestPath)
        {
            try
            {
                var manifest   = JsonSerializer.Deserialize<ManifestJson>(File.ReadAllText(manifestPath), JsonOpts)!;
                // Skip consolidated reports to prevent double-counting on re-scans
                if (string.Equals(manifest.reportType, "consolidated", StringComparison.OrdinalIgnoreCase))
                    return null;
                var reportName = manifest.reportName;

                var rows       = JsonSerializer.Deserialize<List<ReportRow>>(File.ReadAllText(dataJsonPath), JsonOpts) ?? [];
                var testResults = rows.Select(r => ToTestResult(r, reportName)).ToList();

                return new DiscoveredReport
                {
                    ReportName = reportName,
                    SourcePath = Path.GetDirectoryName(dataJsonPath)!,
                    SourceType = ReportSourceType.FolderBased,
                    TestCount  = testResults.Count,
                    Results    = testResults
                };
            }
            catch
            {
                return null;
            }
        }

        // ── Single-file HTML reader ─────────────────────────────────────────────

        private static DiscoveredReport? TryReadSingleFileReport(string htmlPath)
        {
            try
            {
                var html = File.ReadAllText(htmlPath);

                // Must have the generator marker — skip unrelated HTML files
                if (!html.Contains("<meta name=\"generator\" content=\"SimpleSeleniumSupport\">",
                        StringComparison.OrdinalIgnoreCase))
                    return null;

                // Skip consolidated reports to prevent double-counting on re-scans
                var reportType = ExtractMetaContent(html, "sss:report-type");
                if (string.Equals(reportType, "consolidated", StringComparison.OrdinalIgnoreCase))
                    return null;

                var reportName = System.Net.WebUtility.HtmlDecode(
                    ExtractMetaContent(html, "sss:report-name"));

                var json = ExtractAllRowsJson(html);
                if (json == null) return null;

                var rows       = JsonSerializer.Deserialize<List<ReportRow>>(json, JsonOpts) ?? [];
                var testResults = rows.Select(r => ToTestResult(r, reportName)).ToList();

                return new DiscoveredReport
                {
                    ReportName = reportName,
                    SourcePath = htmlPath,
                    SourceType = ReportSourceType.SingleFile,
                    TestCount  = testResults.Count,
                    Results    = testResults
                };
            }
            catch
            {
                return null;
            }
        }

        // ── Extraction helpers ──────────────────────────────────────────────────

        private static string ExtractMetaContent(string html, string metaName)
        {
            var match = Regex.Match(html,
                $"""<meta\s+name="{Regex.Escape(metaName)}"\s+content="([^"]*)"[^>]*>""",
                RegexOptions.IgnoreCase);
            return match.Success ? match.Groups[1].Value : "";
        }

        private static string? ExtractAllRowsJson(string html)
        {
            const string startMarker = "ALL_ROWS = [";

            int start = html.IndexOf(startMarker, StringComparison.Ordinal);
            if (start < 0) return null;
            start += "ALL_ROWS = ".Length;  // point to the opening '['

            // Current format: ALL_ROWS = [...];\ndocument.getElementById(...)
            // Legacy format:  ALL_ROWS = [...]; populateDropdowns(...)
            int end = html.IndexOf(";\ndocument.getElementById('load-msg')", start, StringComparison.Ordinal);
            if (end < 0)
                end = html.IndexOf("; populateDropdowns", start, StringComparison.Ordinal);
            if (end < 0)
                end = html.IndexOf(";\npopulateDropdowns", start, StringComparison.Ordinal);
            if (end < 0) return null;

            // Reverse the </script → <\/script escaping applied when writing the single-file report
            return html.Substring(start, end - start)
                       .Replace(@"<\/script", "</script", StringComparison.OrdinalIgnoreCase);
        }

        // ── Row → TestResult mapping ────────────────────────────────────────────

        private static TestResult ToTestResult(ReportRow row, string fallbackRunName) => new()
        {
            RunName          = !string.IsNullOrEmpty(row.runName) ? row.runName : fallbackRunName,
            TestName         = row.testName,
            TestSuite        = NullIfEmpty(row.testSuite),
            FullName         = NullIfEmpty(row.fullName),
            Category         = NullIfEmpty(row.category),
            Tags             = NullIfEmpty(row.tags),
            Status           = ParseStatus(row.status),
            DurationMs       = row.durationMs,
            StartTime        = row.startTime,
            Browser          = NullIfEmpty(row.browser),
            Environment      = NullIfEmpty(row.environment),
            MachineName      = NullIfEmpty(row.machineName),
            ExceptionType    = NullIfEmpty(row.exceptionType),
            ExceptionMessage = NullIfEmpty(row.exceptionMsg),
            StackTrace       = NullIfEmpty(row.stackTrace),
            AssertMessage    = NullIfEmpty(row.assertMsg),
            SkipReason       = NullIfEmpty(row.skipReason),
            ScreenshotPath   = NullIfEmpty(row.screenshot),
            ScreencastPath   = NullIfEmpty(row.screencast),
            DiagnosticsFolder = NullIfEmpty(row.diagnostics),
            NetworkHarPath   = NullIfEmpty(row.networkHar),
            NetworkExcelPath = NullIfEmpty(row.networkExcel),
            AiAnalysis       = NullIfEmpty(row.aiAnalysis),
            AiClassification = NullIfEmpty(row.aiClassification),
            AiConfidence     = NullIfEmpty(row.aiConfidence),
            CustomProperties = row.customProps ?? new()
        };

        private static string? NullIfEmpty(string? s) =>
            string.IsNullOrEmpty(s) ? null : s;

        private static TestStatus ParseStatus(string? s) => s?.ToLowerInvariant() switch
        {
            "fail"  => TestStatus.Fail,
            "error" => TestStatus.Error,
            "skip"  => TestStatus.Skip,
            _       => TestStatus.Pass
        };

        // ── JSON options ────────────────────────────────────────────────────────

        private static readonly JsonSerializerOptions JsonOpts = new()
        {
            PropertyNameCaseInsensitive = true
        };

        // ── Internal DTO types ──────────────────────────────────────────────────

        // Mirrors the camelCase shape written by TestRunReportExporter.BuildRow()
        // and serialised to data.json / embedded in single-file HTML reports.
        private sealed class ReportRow
        {
            public string?  runName        { get; set; }
            public string   testName       { get; set; } = "";
            public string?  testSuite      { get; set; }
            public string?  fullName       { get; set; }
            public string?  category       { get; set; }
            public string?  tags           { get; set; }
            public string   status         { get; set; } = "Pass";
            public double   durationMs     { get; set; }
            public DateTime startTime      { get; set; }
            public string?  browser        { get; set; }
            public string?  environment    { get; set; }
            public string?  machineName    { get; set; }
            public string?  exceptionType  { get; set; }
            public string?  exceptionMsg   { get; set; }   // ExceptionMessage
            public string?  stackTrace     { get; set; }
            public string?  assertMsg      { get; set; }   // AssertMessage
            public string?  skipReason     { get; set; }
            public string?  screenshot     { get; set; }   // ScreenshotPath
            public string?  screencast     { get; set; }   // ScreencastPath
            public string?  diagnostics    { get; set; }   // DiagnosticsFolder
            public string?  networkHar     { get; set; }   // NetworkHarPath
            public string?  networkExcel   { get; set; }   // NetworkExcelPath
            public string?  aiAnalysis        { get; set; }
            public string?  aiClassification  { get; set; }
            public string?  aiConfidence      { get; set; }
            public Dictionary<string, string>? customProps { get; set; }
        }

        // Mirrors the shape written to manifest.json
        private sealed class ManifestJson
        {
            public string  reportName  { get; set; } = "";
            public string? reportType  { get; set; }  // "consolidated" → skip on re-scan
        }
    }
}
